import type { ReactNode } from "react";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import type { ScanStatistics } from "@/types/statistics";

type Props = {
  securityScore: number;
  overallRisk: string;
  statistics: ScanStatistics;
};

const statisticCards: Array<{
  key: keyof ScanStatistics;
  title: string;
}> = [
  { key: "critical", title: "Critical" },
  { key: "high", title: "High" },
  { key: "medium", title: "Medium" },
  { key: "low", title: "Low" },
  { key: "info", title: "Info" },
  { key: "total", title: "Total" },
];

export function ExecutiveSummary({
  securityScore,
  overallRisk,
  statistics,
}: Props) {
  return (
    <Card id="executive-summary">
      <CardHeader>
        <CardTitle className="text-4xl">Security Assessment Report</CardTitle>
        <CardDescription>Generated by VibeSec AI Security Engineer</CardDescription>
      </CardHeader>

      <CardContent>
        <div className="grid gap-8 lg:grid-cols-2">
          <MetricPanel label="Security Score">
            <p className="mt-2 text-6xl font-bold">{securityScore}</p>
            <p className="text-xl text-muted-foreground">/100</p>
          </MetricPanel>

          <MetricPanel label="Overall Risk">
            <p className="mt-4 text-4xl font-bold">{overallRisk}</p>
          </MetricPanel>
        </div>

        <div className="mt-8 grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-6">
          {statisticCards.map((card) => (
            <MetricPanel key={card.key} label={card.title} className="p-4 text-center">
              <p className="mt-2 text-3xl font-bold">{statistics[card.key]}</p>
            </MetricPanel>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}

function MetricPanel({
  label,
  children,
  className = "p-6",
}: {
  label: string;
  children: ReactNode;
  className?: string;
}) {
  return (
    <div className={`rounded-lg border border-border ${className}`}>
      <p className="text-sm text-muted-foreground">{label}</p>
      {children}
    </div>
  );
}
