type Statistics = {
    critical: number;
    high: number;
    medium: number;
    low: number;
    info: number;
    total: number;
  };
  
  type Props = {
    securityScore: number;
    overallRisk: string;
    statistics: Statistics;
  };
  
  export function ExecutiveSummary({
    securityScore,
    overallRisk,
    statistics,
  }: Props) {
    return (
      <section className="rounded-xl border bg-card p-8 shadow-sm">
        <h1 className="text-4xl font-bold">
          Security Assessment Report
        </h1>
  
        <p className="mt-2 text-muted-foreground">
          Generated by VibeSec AI Security Engineer
        </p>
  
        <div className="mt-8 grid gap-8 lg:grid-cols-2">
  
          <div className="rounded-lg border p-6">
            <p className="text-sm text-muted-foreground">
              Security Score
            </p>
  
            <p className="mt-2 text-6xl font-bold">
              {securityScore}
            </p>
  
            <p className="text-xl text-muted-foreground">
              /100
            </p>
          </div>
  
          <div className="rounded-lg border p-6">
            <p className="text-sm text-muted-foreground">
              Overall Risk
            </p>
  
            <p className="mt-4 text-4xl font-bold">
              {overallRisk}
            </p>
          </div>
        </div>
  
        <div className="mt-8 grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-6">
  
          <StatCard
            title="Critical"
            value={statistics.critical}
          />
  
          <StatCard
            title="High"
            value={statistics.high}
          />
  
          <StatCard
            title="Medium"
            value={statistics.medium}
          />
  
          <StatCard
            title="Low"
            value={statistics.low}
          />
  
          <StatCard
            title="Info"
            value={statistics.info}
          />
  
          <StatCard
            title="Total"
            value={statistics.total}
          />
        </div>
      </section>
    );
  }
  
  function StatCard({
    title,
    value,
  }: {
    title: string;
    value: number;
  }) {
    return (
      <div className="rounded-lg border p-4 text-center">
        <p className="text-sm text-muted-foreground">
          {title}
        </p>
  
        <p className="mt-2 text-3xl font-bold">
          {value}
        </p>
      </div>
    );
  }